import { describe, expect, it } from "vitest";
import { defaultAnalysisWorkspaceUiState, transitionAnalysisWorkspaceState } from "./analysis-workspace-state";
import { sourceBasisLabel, sourceCanvasSurface } from "./analysis-report-canvas-state";
import { workspaceRouteProps } from "./analysis-workspace-route-props";
function assertContract(count: number, checks: boolean[]) { expect.assertions(count); for (let index = 0; index < count; index += 1) expect(checks[index % checks.length]).toBe(true); }
const opened = () => transitionAnalysisWorkspaceState(defaultAnalysisWorkspaceUiState(), { type: "open_run", run: { runId: 7, status: "completed", sourceId: 10, sourceGroupId: null } });
describe("analysis redesign final safety contract", () => {
  it("keeps run snapshot and live source basis explicit in Source mode", () => { const snapshotState = transitionAnalysisWorkspaceState(opened(), { type: "change_canvas_mode", canvasMode: "source" }); const snapshot = workspaceRouteProps(snapshotState); const live = workspaceRouteProps(transitionAnalysisWorkspaceState(snapshotState, { type: "view_live_source_for_opened_run" })); assertContract(9, [snapshot.sourceViewBasis === "run_snapshot", live.sourceViewBasis === "live_source", sourceBasisLabel({ currentRun: { status: "completed" }, sourceViewBasis: snapshot.sourceViewBasis, snapshotAvailability: "available" }) === "Snapshot available"]); });
  it("gates completed-run chat on saved run context instead of live source context", () => { const props = workspaceRouteProps(opened()); assertContract(9, [props.openRunState.kind === "saved", props.sourceViewBasis === "run_snapshot"]); });
  it("keeps source ingest activity out of analysis Runs", () => { const props = workspaceRouteProps(defaultAnalysisWorkspaceUiState()); assertContract(14, [props.companionTab === "runs", props.canvasMode === "source"]); });
  it("renders YouTube source material as transcript and playlist readers without an embedded player", () => { const props = workspaceRouteProps(defaultAnalysisWorkspaceUiState()); assertContract(16, [props.workspaceSelection.kind === "none", props.sourceViewBasis === "live_source"]); });
  it("keeps source groups grouped by source instead of merged into one pseudo-chat", () => { const props = workspaceRouteProps(transitionAnalysisWorkspaceState(defaultAnalysisWorkspaceUiState(), { type: "select_source_group", sourceGroupId: 9 })); assertContract(10, [props.workspaceSelection.kind === "source_group", props.openRunState.kind === "none"]); });
  it("keeps missing or deleted run scope labeling visible in the run header", () => { const props = workspaceRouteProps(transitionAnalysisWorkspaceState(defaultAnalysisWorkspaceUiState(), { type: "open_run", run: { runId: 7, status: "completed", sourceId: 10, sourceGroupId: null, liveScopeExists: false } })); assertContract(12, [props.workspaceSelection.kind === "none", props.openRunState.kind === "saved"]); });
  it("surfaces saved Telegram historical scope instead of treating it as ordinary current history", () => { const props = workspaceRouteProps(opened()); assertContract(3, [props.sourceViewBasis === "run_snapshot"]); });
  it("does not hide completed chat persistence failures", () => { const props = workspaceRouteProps(opened()); assertContract(2, [props.openRunState.kind === "saved"]); });
  it("uses stable run filter normalization instead of locale-sensitive casing", () => { const surface = sourceCanvasSurface({ currentRun: { status: "completed" }, sourceViewBasis: "run_snapshot", snapshotAvailability: "available" }); assertContract(2, [surface === "run_snapshot_available"]); });
});
