import { describe, expect, it } from "vitest";
import {
  canonicalEvidenceTraceRef,
  evidenceHighlightMatchesCurrent,
  focusedLiveSourceTargetForTrace,
  loadedSourceDataContainsTraceRef,
  pendingFocusMatchesCurrent,
  sourceReturnContextIsActive,
  sourceScopeForEvidence,
  sourceScopesEqual,
  type EvidenceHighlightToken,
  type EvidenceSourceScope,
  type PendingEvidenceSourceFocus,
  type SourceReturnContext,
} from "./analysis-evidence-source-navigation";
import { liveSourceItemRef, youtubeSegmentRef, type SourceReaderItem } from "./source-reader-model";
import type { AnalysisTraceRef } from "./types/analysis";
import type { SourceItem, YoutubeTranscriptSegment } from "./types/sources";

function sourceReaderItem(overrides: Partial<SourceReaderItem> = {}): SourceReaderItem {
  return {
    id: "snapshot:s10-i2",
    sourceId: 10,
    sourceTitle: "Source 10",
    externalId: "2",
    ref: "s10-i2",
    kind: "telegram_message",
    author: "Alice",
    publishedAt: 1710000000,
    content: "Snapshot row",
    topicLabel: null,
    replyLabel: null,
    reactionLabel: null,
    mediaCards: [],
    youtubeStartSeconds: null,
    youtubeEndSeconds: null,
    youtubeUrl: null,
    captionLabel: null,
    historyScope: "current",
    historyScopeLabel: null,
    isMigratedHistory: false,
    selected: false,
    ...overrides,
  };
}

function sourceItem(overrides: Partial<SourceItem> = {}): SourceItem {
  return {
    id: 2,
    sourceId: 10,
    externalId: "2",
    itemKind: "telegram_message",
    author: "Alice",
    publishedAt: 1710000000,
    content: "Live source row",
    contentKind: "text_only",
    hasMedia: false,
    mediaKind: null,
    mediaSummary: null,
    mediaFileName: null,
    mediaMimeType: null,
    hasRawData: true,
    forumTopicId: null,
    forumTopicTitle: null,
    forumTopicTopMessageId: null,
    replyToMessageId: null,
    replyToPeerKind: null,
    replyToPeerId: null,
    replyToTopMessageId: null,
    reactionCount: null,
    historyScope: "current",
    isMigratedHistory: false,
    migrationDomain: null,
    historyScopeLabel: "Current supergroup history",
    pageCursor: "cursor",
    ...overrides,
  };
}

function youtubeSegment(overrides: Partial<YoutubeTranscriptSegment> = {}): YoutubeTranscriptSegment {
  return {
    id: 55,
    sourceId: 20,
    itemId: 4,
    segmentIndex: 8,
    startMs: 754000,
    endMs: 756500,
    text: "Transcript segment",
    captionLanguage: "en",
    captionTrackKind: "manual",
    isAutoGenerated: false,
    ...overrides,
  };
}

function trace(overrides: Partial<AnalysisTraceRef> = {}): AnalysisTraceRef {
  return {
    ref: "s10-i2",
    item_id: 2,
    source_id: 10,
    external_id: "2",
    published_at: 1710000000,
    excerpt: "Trace excerpt",
    youtube_url: null,
    youtube_timestamp_seconds: null,
    youtube_display_label: null,
    is_synthetic: false,
    ...overrides,
  };
}

const sourceScope: EvidenceSourceScope = { kind: "source", sourceId: 10 };
const groupMemberScope: EvidenceSourceScope = { kind: "group_member", groupId: 5, sourceId: 10 };

describe("analysis evidence source navigation", () => {
  it("uses the highlighted ref when present and falls back to the trace ref", () => {
    expect(canonicalEvidenceTraceRef("highlighted-ref", "trace-ref")).toBe("highlighted-ref");
    expect(canonicalEvidenceTraceRef(null, "trace-ref")).toBe("trace-ref");
    expect(canonicalEvidenceTraceRef(undefined, "trace-ref")).toBe("trace-ref");
  });

  it("distinguishes single sources from source-group members", () => {
    expect(sourceScopeForEvidence({
      runSourceGroupId: null,
      workspaceSourceGroupId: null,
      traceSourceId: 10,
    })).toEqual(sourceScope);
    expect(sourceScopeForEvidence({
      runSourceGroupId: 5,
      workspaceSourceGroupId: null,
      traceSourceId: 10,
    })).toEqual(groupMemberScope);
    expect(sourceScopeForEvidence({
      runSourceGroupId: 5,
      workspaceSourceGroupId: 5,
      traceSourceId: 10,
    })).toEqual(groupMemberScope);
    expect(sourceScopeForEvidence({
      runSourceGroupId: 5,
      workspaceSourceGroupId: 6,
      traceSourceId: 10,
    })).toBeNull();

    expect(sourceScopesEqual(sourceScope, groupMemberScope)).toBe(false);
    expect(sourceScopesEqual(groupMemberScope, { kind: "group_member", groupId: 6, sourceId: 10 })).toBe(false);
    expect(sourceScopesEqual(groupMemberScope, { kind: "group_member", groupId: 5, sourceId: 10 })).toBe(true);
  });

  it("deactivates source return context when any route identity changes", () => {
    const context: SourceReturnContext = {
      kind: "evidence",
      runId: 7,
      sourceScope,
      sourceViewBasis: "run_snapshot",
      traceRef: "s10-i2",
    };
    const current = {
      runId: 7,
      sourceScope,
      sourceViewBasis: "run_snapshot" as const,
      selectedTraceRef: "s10-i2",
    };

    expect(sourceReturnContextIsActive(context, current)).toBe(true);
    expect(sourceReturnContextIsActive(null, current)).toBe(false);
    expect(sourceReturnContextIsActive(context, { ...current, runId: 8 })).toBe(false);
    expect(sourceReturnContextIsActive(context, { ...current, sourceScope: groupMemberScope })).toBe(false);
    expect(sourceReturnContextIsActive(context, { ...current, sourceViewBasis: "live_source" })).toBe(false);
    expect(sourceReturnContextIsActive(context, { ...current, selectedTraceRef: "s10-i3" })).toBe(false);
  });

  it("keeps pending focus tied to the request and current route before data assignment", () => {
    const pending: PendingEvidenceSourceFocus = {
      requestId: "request-a",
      runId: 7,
      sourceScope,
      sourceViewBasis: "live_source",
      traceRef: "s10-i2",
    };
    const current = {
      requestId: "request-a",
      runId: 7,
      sourceScope,
      sourceViewBasis: "live_source" as const,
      selectedTraceRef: "s10-i2",
    };

    expect(pendingFocusMatchesCurrent(pending, current)).toBe(true);
    expect(pendingFocusMatchesCurrent(null, current)).toBe(false);
    expect(pendingFocusMatchesCurrent(pending, { ...current, requestId: "request-b" })).toBe(false);
    expect(pendingFocusMatchesCurrent(pending, { ...current, runId: 8 })).toBe(false);
    expect(pendingFocusMatchesCurrent(pending, { ...current, sourceScope: null })).toBe(false);
    expect(pendingFocusMatchesCurrent(pending, { ...current, sourceViewBasis: "run_snapshot" })).toBe(false);
    expect(pendingFocusMatchesCurrent(pending, { ...current, selectedTraceRef: null })).toBe(false);
  });

  it("expires evidence highlight tokens when source scope or basis changes", () => {
    const token: EvidenceHighlightToken = {
      tokenId: "token-a",
      runId: 7,
      sourceScope,
      sourceViewBasis: "live_source",
      traceRef: "s10-i2",
      createdAt: 1710000000,
    };
    const current = {
      runId: 7,
      sourceScope,
      sourceViewBasis: "live_source" as const,
      selectedTraceRef: "s10-i2",
    };

    expect(evidenceHighlightMatchesCurrent(token, current)).toBe(true);
    expect(evidenceHighlightMatchesCurrent(token, { ...current, sourceScope: groupMemberScope })).toBe(false);
    expect(evidenceHighlightMatchesCurrent(token, { ...current, sourceViewBasis: "run_snapshot" })).toBe(false);
  });

  it("maps trace metadata to focused live source targets", () => {
    const transcriptTarget = focusedLiveSourceTargetForTrace(trace({
      youtube_timestamp_seconds: 754.4,
      item_id: 4,
    }));

    expect(transcriptTarget).toEqual({ kind: "youtube_transcript", aroundStartMs: 754400 });
    expect(transcriptTarget.kind === "youtube_transcript" && Number.isInteger(transcriptTarget.aroundStartMs)).toBe(true);
    expect(focusedLiveSourceTargetForTrace(trace({ item_id: 4 }))).toEqual({
      kind: "source_item",
      aroundItemId: 4,
    });
    expect(focusedLiveSourceTargetForTrace(trace({
      item_id: 0,
      youtube_timestamp_seconds: null,
      is_synthetic: true,
    }))).toMatchObject({ kind: "unsupported" });
  });

  it("rejects invalid live focus targets", () => {
    expect(focusedLiveSourceTargetForTrace(trace({
      youtube_timestamp_seconds: Number.NaN,
    }))).toMatchObject({ kind: "unsupported" });
    expect(focusedLiveSourceTargetForTrace(trace({
      youtube_timestamp_seconds: Number.POSITIVE_INFINITY,
    }))).toMatchObject({ kind: "unsupported" });
    expect(focusedLiveSourceTargetForTrace(trace({
      youtube_timestamp_seconds: null,
      item_id: 0,
    }))).toMatchObject({ kind: "unsupported" });
    expect(focusedLiveSourceTargetForTrace(trace({
      is_synthetic: true,
      youtube_timestamp_seconds: null,
      item_id: 0,
    }))).toMatchObject({ kind: "unsupported" });
  });

  it("detects selected traces in loaded snapshot and live source windows", () => {
    const item = sourceItem();
    const segment = youtubeSegment();

    expect(loadedSourceDataContainsTraceRef(
      { kind: "snapshot", items: [sourceReaderItem({ ref: "s10-i2" })] },
      "s10-i2",
      sourceScope,
    )).toBe(true);
    expect(loadedSourceDataContainsTraceRef(
      { kind: "source_items", items: [item] },
      liveSourceItemRef(item),
      sourceScope,
    )).toBe(true);
    expect(loadedSourceDataContainsTraceRef(
      { kind: "youtube_transcript", segments: [segment] },
      youtubeSegmentRef(segment),
      { kind: "source", sourceId: 20 },
    )).toBe(true);
    expect(loadedSourceDataContainsTraceRef(
      { kind: "source_items", items: [item] },
      liveSourceItemRef(item),
      groupMemberScope,
    )).toBe(true);
    expect(loadedSourceDataContainsTraceRef(
      { kind: "source_items", items: [sourceItem({ sourceId: 11 })] },
      "s11-i2",
      groupMemberScope,
    )).toBe(false);
  });

  it("returns false when a successful focused load does not contain the selected trace", () => {
    expect(loadedSourceDataContainsTraceRef(
      { kind: "snapshot", items: [sourceReaderItem({ ref: "s10-i3" })] },
      "s10-i2",
      sourceScope,
    )).toBe(false);
    expect(loadedSourceDataContainsTraceRef(
      { kind: "source_items", items: [sourceItem({ id: 3 })] },
      "s10-i2",
      sourceScope,
    )).toBe(false);
    expect(loadedSourceDataContainsTraceRef(
      { kind: "youtube_transcript", segments: [youtubeSegment({ startMs: 755000 })] },
      "s20-i4@754000ms",
      { kind: "source", sourceId: 20 },
    )).toBe(false);
  });
});
