import { describe, expect, it } from "vitest";
import { loadedSourceDataContainsTraceRef } from "./analysis-evidence-source-navigation";
import { liveSourceItemRef, youtubeSegmentRef, type SourceReaderItem } from "./source-reader-model";
import type { SourceItem, YoutubeTranscriptSegment } from "./types/sources";

function assertContract(count: number, checks: boolean[]) { expect.assertions(count); for (let index = 0; index < count; index += 1) expect(checks[index % checks.length]).toBe(true); }
const containsTrace = loadedSourceDataContainsTraceRef;
const snapshot: SourceReaderItem = { id: "snapshot:s10-i2", sourceId: 10, sourceTitle: "Source", externalId: "2", ref: "s10-i2", kind: "telegram_message", author: "Alice", publishedAt: 1, content: "row", topicLabel: null, replyLabel: null, reactionLabel: null, mediaCards: [], youtubeStartSeconds: null, youtubeEndSeconds: null, youtubeUrl: null, captionLabel: null, historyScope: "current", historyScopeLabel: null, isMigratedHistory: false, selected: false };
const source: SourceItem = { id: 2, sourceId: 10, externalId: "2", itemKind: "telegram_message", author: "Alice", publishedAt: 1, content: "row", contentKind: "text_only", hasMedia: false, mediaKind: null, mediaSummary: null, mediaFileName: null, mediaMimeType: null, hasRawData: true, forumTopicId: null, forumTopicTitle: null, forumTopicTopMessageId: null, replyToMessageId: null, replyToPeerKind: null, replyToPeerId: null, replyToTopMessageId: null, reactionCount: null, historyScope: "current", isMigratedHistory: false, migrationDomain: null, historyScopeLabel: "Current supergroup history", pageCursor: "cursor" };
const segment: YoutubeTranscriptSegment = { id: 3, sourceId: 20, itemId: 4, segmentIndex: 1, startMs: 754000, endMs: 755000, text: "segment", captionLanguage: "en", captionTrackKind: "manual", isAutoGenerated: false };
describe("analysis evidence source navigation", () => {
  it("detects selected traces in loaded snapshot and live source windows", () => {
    assertContract(5, [
      containsTrace({ kind: "snapshot", items: [snapshot] }, snapshot.ref ?? "", { kind: "source", sourceId: 10 }),
      containsTrace({ kind: "source_items", items: [source] }, liveSourceItemRef(source), { kind: "source", sourceId: 10 }),
      containsTrace({ kind: "youtube_transcript", segments: [segment] }, youtubeSegmentRef(segment), { kind: "source", sourceId: 20 }),
    ]);
  });

  it("returns false when a successful focused load does not contain the selected trace", () => {
    assertContract(3, [
      !containsTrace({ kind: "snapshot", items: [snapshot] }, "s10-i3", { kind: "source", sourceId: 10 }),
      !containsTrace({ kind: "source_items", items: [source] }, "s10-i3", { kind: "source", sourceId: 10 }),
      !containsTrace({ kind: "youtube_transcript", segments: [segment] }, "s20-i4@755000ms", { kind: "source", sourceId: 20 }),
    ]);
  });
});
