import { describe, expect, it, vi } from "vitest";
import {
  fetchSourceGroupPage,
  fetchLiveGroupReaderPage,
  fetchFocusedLiveSourceData,
  fetchBeforeReaderReveal,
  fetchSourceItemsPage,
  loadYoutubeTranscriptPage,
  sourceActivityJobs,
  sourceReaderSurfaceState,
} from "./analysis-source-readers-route-runtime";
import {
  focusedLiveSourceTargetForTrace,
  sourceDataContainsTraceRef,
} from "./analysis-evidence-source-navigation";
import { focusedSourceLoadExit } from "./analysis-route-effects";
import { loadRunSnapshotPage } from "./analysis-route-runtime";
import { youtubeSegmentRef } from "./source-reader-model";

const source = (overrides: Record<string, unknown> = {}) => ({
  id: 7,
  sourceType: "telegram",
  sourceSubtype: "supergroup",
  ...overrides,
});

const sourceItem = (overrides: Record<string, unknown> = {}) => ({
  id: 41,
  sourceId: 7,
  externalId: "message:41",
  itemKind: "message",
  author: "Researcher",
  publishedAt: 900,
  content: "Evidence item",
  contentKind: "text",
  hasMedia: false,
  mediaKind: null,
  mediaSummary: null,
  mediaFileName: null,
  mediaMimeType: null,
  hasRawData: true,
  forumTopicId: null,
  forumTopicTitle: null,
  forumTopicTopMessageId: null,
  replyToMessageId: null,
  replyToPeerKind: null,
  replyToPeerId: null,
  replyToTopMessageId: null,
  reactionCount: null,
  historyScope: "current" as const,
  isMigratedHistory: false,
  migrationDomain: null,
  historyScopeLabel: "Current supergroup history" as const,
  pageCursor: "opaque:cursor:41",
  ...overrides,
});

const segment = (overrides: Record<string, unknown> = {}) => ({
  id: 51,
  sourceId: 7,
  itemId: 41,
  segmentIndex: 0,
  startMs: 12_000,
  endMs: 15_000,
  text: "Transcript evidence",
  captionLanguage: "en",
  captionTrackKind: "manual",
  isAutoGenerated: false,
  ...overrides,
});

const topic = (key: string, topicId: number) => ({
  kind: "topic" as const,
  key,
  title: `Topic ${topicId}`,
  messageCount: 4,
  topicId,
  topMessageId: 100 + topicId,
  iconColor: null,
  iconEmojiId: null,
  isClosed: false,
  isPinned: false,
  isHidden: false,
  isDeleted: false,
  sortOrder: topicId,
});

describe("analysis source reader route wiring", () => {
  it("loads live source group pages per member without closing the opened run", async () => {
    const cursor = { startMs: 12_000, segmentId: 51 };
    const nextCursor = { startMs: 15_000, segmentId: 52 };
    const listSourceItems = vi.fn(() => { throw new Error("transcript paging fell through to generic items"); });
    const listYoutubeTranscriptSegments = vi.fn().mockResolvedValue({ segments: [segment({ id: 52, startMs: 15_000 })], nextCursor, hasMore: true });
    const page = await fetchLiveGroupReaderPage({ source: source({ sourceType: "youtube", sourceSubtype: "video" }), transcriptActive: true, transcriptCursor: cursor, listSourceItems, listYoutubeTranscriptSegments });

    expect(listYoutubeTranscriptSegments).toHaveBeenCalledOnce();
    expect(listYoutubeTranscriptSegments).toHaveBeenCalledWith({ sourceId: 7, after: cursor, limit: 80, searchQuery: null, aroundStartMs: null });
    expect(listSourceItems).not.toHaveBeenCalled();
    expect(page.kind).toBe("youtube_transcript");
    expect(page.kind === "youtube_transcript" ? page.page.segments[0]?.id : null).toBe(52);
    expect(page.kind === "youtube_transcript" ? page.page.nextCursor : null).toBe(nextCursor);
    expect(page.kind === "youtube_transcript" ? page.page.hasMore : false).toBe(true);
  });

  it("loads YouTube transcript segments through a paged API", async () => {
    const cursor = { startMs: 11_000, segmentId: 50 };
    const nextCursor = { startMs: 12_000, segmentId: 51 };
    const listYoutubeTranscriptSegments = vi.fn().mockResolvedValue({ segments: [segment()], nextCursor, hasMore: true });
    const page = await loadYoutubeTranscriptPage({ sourceId: 7, after: cursor, searchQuery: "  topic  ", aroundStartMs: null, limit: 80, listYoutubeTranscriptSegments });

    expect(listYoutubeTranscriptSegments).toHaveBeenCalledOnce();
    expect(listYoutubeTranscriptSegments).toHaveBeenCalledWith({ sourceId: 7, after: cursor, limit: 80, searchQuery: "topic", aroundStartMs: null });
    expect(page.segments).toEqual([segment()]);
    expect(page.nextCursor).toBe(nextCursor);
    expect(page.hasMore).toBe(true);
  });

  it("passes source reader props into ReportSourceSurface", () => {
    const onLoadMoreSourceItems = vi.fn();
    const onLoadMoreYoutubeTranscriptSegments = vi.fn();
    const onLoadLiveGroupSourcePage = vi.fn();
    const onChangeSelectedGroupSourceId = vi.fn();
    const onChangeSelectedTopicKey = vi.fn();
    const state = sourceReaderSurfaceState({
      youtubeTranscriptSegments: [segment()], groupLiveItemsBySource: { 7: [sourceItem()] },
      groupLiveTranscriptSegmentsBySource: { 7: [segment()] }, selectedGroupSourceId: 7,
      sourceTopics: [topic("topic:1", 1), topic("topic:2", 2)], loadingSourceTopics: false, selectedTopicKey: "topic:1",
      showTopicSelector: true, sourceItemsHasMore: true, onLoadMoreSourceItems,
      onLoadMoreYoutubeTranscriptSegments, onLoadLiveGroupSourcePage, onChangeSelectedGroupSourceId, onChangeSelectedTopicKey,
    });

    expect(state.youtubeTranscriptSegments).toHaveLength(1);
    expect(state.groupLiveItemsBySource[7]).toHaveLength(1);
    expect(state.groupLiveTranscriptSegmentsBySource[7]).toHaveLength(1);
    expect(state.selectedGroupSourceId).toBe(7);
    expect(state.sourceTopics).toHaveLength(2);
    expect(state.loadingSourceTopics).toBe(false);
    expect(state.selectedTopicKey).toBe("topic:1");
    expect(state.showTopicSelector).toBe(true);
    expect(state.sourceItemsHasMore).toBe(true);
    state.onLoadMoreSourceItems();
    state.onLoadMoreYoutubeTranscriptSegments();
    state.onLoadLiveGroupSourcePage(7);
    state.onChangeSelectedGroupSourceId(7);
    state.onChangeSelectedTopicKey("topic:2");
    expect(onLoadMoreSourceItems).toHaveBeenCalledOnce();
    expect(onLoadMoreYoutubeTranscriptSegments).toHaveBeenCalledOnce();
    expect(onLoadLiveGroupSourcePage).toHaveBeenCalledWith(7);
    expect(onChangeSelectedGroupSourceId).toHaveBeenCalledWith(7);
    expect(onChangeSelectedTopicKey).toHaveBeenCalledWith("topic:2");
  });

  it("pages live single-source material without changing the selected topic filter", async () => {
    const listSourceItems = vi.fn().mockResolvedValue([sourceItem()]);
    const page = await fetchSourceItemsPage({ source: source({ sourceType: "rss" }), limit: 50, beforePublishedAt: 900, beforeCursor: null, historyScope: "merged", topicFilter: { kind: "topic", topicId: 3 }, listSourceItems });

    expect(listSourceItems).toHaveBeenCalledOnce();
    expect(listSourceItems).toHaveBeenCalledWith({ sourceId: 7, limit: 50, beforePublishedAt: 900, beforeCursor: null, historyScope: "current", topicFilter: { kind: "topic", topicId: 3 } });
    expect(page.items).toEqual([sourceItem()]);
    expect(page.beforePublishedAt).toBe(900);
    expect(page.beforeCursor).toBeNull();
    expect(page.historyScope).toBe("current");
    expect(page.topicFilter).toEqual({ kind: "topic", topicId: 3 });
  });

  it("wires Telegram history scope changes through opaque backend cursors", async () => {
    const listSourceItems = vi.fn().mockResolvedValue([sourceItem()]);
    const page = await fetchSourceItemsPage({ source: source(), limit: 50, beforePublishedAt: 900, beforeCursor: "opaque:cursor:42", historyScope: "migrated", topicFilter: null, listSourceItems });

    expect(listSourceItems).toHaveBeenCalledOnce();
    expect(listSourceItems).toHaveBeenCalledWith({ sourceId: 7, limit: 50, beforePublishedAt: null, beforeCursor: "opaque:cursor:42", historyScope: "migrated", topicFilter: null });
    expect(page.beforeCursor).toBe("opaque:cursor:42");
    expect(page.beforePublishedAt).toBeNull();
    expect(page.historyScope).toBe("migrated");
    expect(() => JSON.parse(page.beforeCursor ?? "")).toThrow();
    expect(page.items[0]?.pageCursor).toBe("opaque:cursor:41");
  });

  it("supports run snapshot source filtering through the snapshot-only API", async () => {
    const listMessages = vi.fn().mockResolvedValue({ messages: [{ ref: "trace:7" }], next: null, has_more: false });
    const page = await loadRunSnapshotPage({ runId: 22, sourceId: 7, aroundRef: "trace:7", after: null, limit: 50, listMessages });
    expect(listMessages).toHaveBeenCalledWith({ runId: 22, sourceId: 7, aroundRef: "trace:7", after: null, limit: 50 });
    expect(page.messages).toEqual([{ ref: "trace:7" }]);
    expect(listMessages).toHaveBeenCalledOnce();
  });

  it("includes related playlist-video jobs in selected video source activity", () => {
    const jobs = sourceActivityJobs(7, {
      7: [{ job_id: 1, source_id: 7, related_source_id: null, started_at: 10 }],
      8: [{ job_id: 2, source_id: 8, related_source_id: 7, started_at: 20 }, { job_id: 1, source_id: 8, related_source_id: 7, started_at: 30 }],
    });
    expect(jobs.map((job) => job.job_id)).toEqual([2, 1]);
    expect(jobs[0]?.related_source_id).toBe(7);
    expect(jobs[1]?.source_id).toBe(7);
  });

  it("loads live source pages around the selected trace before source readers scroll", async () => {
    const sequence: string[] = [];
    const target = focusedLiveSourceTargetForTrace({ item_id: 41, youtube_timestamp_seconds: null, is_synthetic: false });
    const listSourceItems = vi.fn().mockResolvedValue([sourceItem()]);
    const page = await fetchBeforeReaderReveal(
      async () => { sequence.push("fetch"); return fetchSourceItemsPage({ source: source(), limit: 50, beforePublishedAt: null, beforeCursor: null, historyScope: "current", topicFilter: null, aroundItemId: target.kind === "source_item" ? target.aroundItemId : null, listSourceItems }); },
      () => { sequence.push("reader"); },
    );

    expect(target.kind).toBe("source_item");
    expect(target.kind === "source_item" ? target.aroundItemId : null).toBe(41);
    expect(listSourceItems).toHaveBeenCalledOnce();
    expect(listSourceItems).toHaveBeenCalledWith(expect.objectContaining({ sourceId: 7, aroundItemId: 41 }));
    expect(page.items).toHaveLength(1);
    expect(page.items[0]?.id).toBe(41);
    expect(page.items[0]?.sourceId).toBe(7);
    expect(page.beforeCursor).toBeNull();
    expect(page.beforePublishedAt).toBeNull();
    expect(page.historyScope).toBe("current");
    expect(page.topicFilter).toBeNull();
    expect(page.aroundItemId).toBe(41);
    expect(sequence).toEqual(["fetch", "reader"]);
  });

  it("uses loaded source data matching to gate focused highlight creation", () => {
    const scope = { kind: "source" as const, sourceId: 7 };
    const matching = sourceDataContainsTraceRef({ kind: "source_items", items: [sourceItem()] } as never, "s7-i41", scope);
    const missing = sourceDataContainsTraceRef({ kind: "source_items", items: [sourceItem()] } as never, "s7-i99", scope);
    const transcriptMatch = sourceDataContainsTraceRef({ kind: "youtube_transcript", segments: [segment()] } as never, youtubeSegmentRef(segment() as never), scope);

    expect(matching).toBe(true);
    expect(missing).toBe(false);
    expect(transcriptMatch).toBe(true);
    expect(sourceDataContainsTraceRef({ kind: "source_items", items: [sourceItem({ sourceId: 8 })] } as never, "s7-i41", scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "source_items", items: [sourceItem()] } as never, "s7-i41", { kind: "group_member", groupId: 2, sourceId: 7 })).toBe(true);
    expect(sourceDataContainsTraceRef({ kind: "source_items", items: [sourceItem()] } as never, "s8-i41", scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "youtube_transcript", segments: [segment()] } as never, youtubeSegmentRef(segment({ startMs: 13_000 }) as never), scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "youtube_transcript", segments: [segment({ sourceId: 8 })] } as never, youtubeSegmentRef(segment() as never), scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "source_items", items: [] } as never, "s7-i41", scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "youtube_transcript", segments: [] } as never, youtubeSegmentRef(segment() as never), scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "source_items", items: [sourceItem()] } as never, youtubeSegmentRef(segment() as never), scope)).toBe(false);
  });

  it("matches snapshot, live item, and transcript focused load data without fabricating rows", () => {
    const scope = { kind: "source" as const, sourceId: 7 };
    const snapshotItem = { ref: "trace:snapshot", sourceId: 7 };
    const live = sourceItem();
    const transcript = segment();
    const snapshotMatch = sourceDataContainsTraceRef({ kind: "snapshot", items: [snapshotItem] } as never, "trace:snapshot", scope);
    const liveMatch = sourceDataContainsTraceRef({ kind: "source_items", items: [live] } as never, "s7-i41", scope);
    const transcriptMatch = sourceDataContainsTraceRef({ kind: "youtube_transcript", segments: [transcript] } as never, youtubeSegmentRef(transcript as never), scope);

    expect(snapshotMatch).toBe(true);
    expect(liveMatch).toBe(true);
    expect(transcriptMatch).toBe(true);
    expect(sourceDataContainsTraceRef({ kind: "snapshot", items: [snapshotItem] } as never, "trace:other", scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "snapshot", items: [snapshotItem] } as never, "trace:snapshot", { kind: "source", sourceId: 8 })).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "source_items", items: [live] } as never, "s7-i99", scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "source_items", items: [live] } as never, "s7-i41", { kind: "source", sourceId: 8 })).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "youtube_transcript", segments: [transcript] } as never, youtubeSegmentRef(segment({ startMs: 99_000 }) as never), scope)).toBe(false);
    expect(sourceDataContainsTraceRef({ kind: "youtube_transcript", segments: [transcript] } as never, youtubeSegmentRef(transcript as never), { kind: "source", sourceId: 8 })).toBe(false);
  });

  it("uses the generic single-source item path for source-item targets before transcript loading", async () => {
    const listSourceItems = vi.fn().mockResolvedValue([sourceItem()]);
    const listYoutubeTranscriptSegments = vi.fn(() => { throw new Error("source-item path fell through to transcript"); });
    const target = focusedLiveSourceTargetForTrace({ item_id: 41, youtube_timestamp_seconds: null, is_synthetic: false });
    const result = await fetchFocusedLiveSourceData({ source: source({ sourceType: "youtube", sourceSubtype: "video" }), target, canonicalRef: "s7-i41", scope: { kind: "source", sourceId: 7 }, itemLimit: 50, historyScope: "current", listSourceItems, listYoutubeTranscriptSegments });

    expect(target.kind).toBe("source_item");
    expect(listSourceItems).toHaveBeenCalledOnce();
    expect(listYoutubeTranscriptSegments).not.toHaveBeenCalled();
    expect(listSourceItems).toHaveBeenCalledWith(expect.objectContaining({ sourceId: 7, aroundItemId: 41 }));
    expect(result.kind).toBe("source_items");
    expect(result.containsTarget).toBe(true);
    const transcriptApi = vi.fn().mockResolvedValue({ segments: [segment()], nextCursor: null, hasMore: false });
    const transcriptResult = await fetchFocusedLiveSourceData({ source: source({ sourceType: "youtube", sourceSubtype: "video" }), target: { kind: "youtube_transcript", aroundStartMs: 12_000 }, canonicalRef: youtubeSegmentRef(segment() as never), scope: { kind: "source", sourceId: 7 }, itemLimit: 50, historyScope: "current", listSourceItems: vi.fn(() => { throw new Error("transcript path fell through to source items"); }), listYoutubeTranscriptSegments: transcriptApi });
    expect(transcriptApi).toHaveBeenCalledWith({ sourceId: 7, after: null, limit: 80, searchQuery: null, aroundStartMs: 12_000 });
    expect(transcriptResult.kind).toBe("youtube_transcript");
    expect(transcriptResult.containsTarget).toBe(true);
  });

  it("clears pending focus on focused load success, absence, and request-owned failure through route helpers", () => {
    const request = { requestId: "focus-1", runId: 22, sourceScope: { kind: "source" as const, sourceId: 7 }, sourceViewBasis: "live_source" as const, traceRef: "s7-i41" };
    const current = { pending: request, runId: 22, sourceScope: request.sourceScope, sourceViewBasis: "live_source" as const, selectedTraceRef: "s7-i41" };
    const success = focusedSourceLoadExit(request, current, { kind: "success" });
    const missing = focusedSourceLoadExit(request, current, { kind: "missing_target" });
    const failed = focusedSourceLoadExit(request, current, { kind: "failed", error: new Error("offline") });
    expect(success.accepted).toBe(true);
    expect(success.clearHighlight).toBe(false);
    expect(missing.clearPendingFocus).toBe(true);
    expect(missing.clearHighlight).toBe(true);
    expect(failed.accepted).toBe(true);
    expect(failed.status).toContain("offline");
  });

  it("loads focused source-group YouTube transcript evidence through transcript DTOs", async () => {
    const listYoutubeTranscriptSegments = vi.fn().mockResolvedValue({ segments: [segment()], nextCursor: null, hasMore: false });
    const target = focusedLiveSourceTargetForTrace({ item_id: 0, youtube_timestamp_seconds: 12, is_synthetic: true });
    const page = await loadYoutubeTranscriptPage({ sourceId: 7, after: null, searchQuery: null, aroundStartMs: target.kind === "youtube_transcript" ? target.aroundStartMs : null, limit: 80, listYoutubeTranscriptSegments });
    const scope = { kind: "group_member" as const, groupId: 2, sourceId: 7 };
    const containsTarget = sourceDataContainsTraceRef({ kind: "youtube_transcript", segments: page.segments } as never, youtubeSegmentRef(segment() as never), scope);

    expect(target.kind).toBe("youtube_transcript");
    expect(target.kind === "youtube_transcript" ? target.aroundStartMs : null).toBe(12_000);
    expect(listYoutubeTranscriptSegments).toHaveBeenCalledOnce();
    expect(listYoutubeTranscriptSegments).toHaveBeenCalledWith({ sourceId: 7, after: null, limit: 80, searchQuery: null, aroundStartMs: 12_000 });
    expect(page.segments).toHaveLength(1);
    expect(page.segments[0]?.sourceId).toBe(7);
    expect(page.segments[0]?.startMs).toBe(12_000);
    expect(page.nextCursor).toBeNull();
    expect(page.hasMore).toBe(false);
    expect(containsTarget).toBe(true);
  });
});
