import { describe, expect, it } from "vitest";
import {
  analysisRunMessageToReaderItem,
  formatYoutubeTime,
  groupYoutubeTranscriptItems,
  groupReaderItemsByDay,
  groupReaderItemsBySource,
  sourceFilterOptionsFromGroupMembers,
  sourceFilterOptionsFromReaderItems,
  sourceItemToReaderItem,
  youtubeSegmentToReaderItem,
  youtubeTimestampUrl,
} from "./source-reader-model";
import type { AnalysisRunMessage } from "./types/analysis";
import type { SourceItem, YoutubeTranscriptSegment } from "./types/sources";

function sourceItem(overrides: Partial<SourceItem> = {}): SourceItem {
  return {
    id: 1,
    sourceId: 10,
    externalId: "100",
    itemKind: "telegram_message",
    author: "Alice",
    publishedAt: 1710000000,
    content: "Hello",
    contentKind: "text_only",
    hasMedia: false,
    mediaKind: null,
    mediaSummary: null,
    mediaFileName: null,
    mediaMimeType: null,
    hasRawData: true,
    forumTopicId: null,
    forumTopicTitle: null,
    forumTopicTopMessageId: null,
    replyToMessageId: null,
    replyToPeerKind: null,
    replyToPeerId: null,
    replyToTopMessageId: null,
    reactionCount: null,
    ...overrides,
  };
}

function runMessage(overrides: Partial<AnalysisRunMessage> = {}): AnalysisRunMessage {
  return {
    item_id: 4,
    source_id: 20,
    external_id: "transcript:v1:en:manual",
    author: "Demo Channel",
    published_at: 1710000200,
    ref: "s20-i4@754000ms",
    content: "Transcript text",
    item_kind: "youtube_transcript",
    source_type: "youtube",
    source_subtype: "video",
    metadata_json: {
      canonical_url: "https://www.youtube.com/watch?v=v1",
      start_ms: 754000,
      end_ms: 756500,
      caption_language: "en",
      caption_track_kind: "manual",
      item_kind: "youtube_transcript",
    },
    ...overrides,
  };
}

function youtubeSegment(overrides: Partial<YoutubeTranscriptSegment> = {}): YoutubeTranscriptSegment {
  return {
    id: 55,
    sourceId: 20,
    itemId: 4,
    segmentIndex: 8,
    startMs: 754000,
    endMs: 756500,
    text: "Transcript segment",
    captionLanguage: "en",
    captionTrackKind: "manual",
    isAutoGenerated: false,
    ...overrides,
  };
}

function transcriptItem({
  ref,
  content,
  startMs,
  endMs,
  sourceId = 20,
  captionLanguage = "en",
  captionTrackKind = "manual",
  selectedTraceRef = null,
}: {
  ref: string;
  content: string;
  startMs: number | null;
  endMs: number | null;
  sourceId?: number;
  captionLanguage?: string | null;
  captionTrackKind?: string | null;
  selectedTraceRef?: string | null;
}) {
  return analysisRunMessageToReaderItem(
    runMessage({
      source_id: sourceId,
      ref,
      content,
      metadata_json: {
        canonical_url: "https://www.youtube.com/watch?v=v1",
        start_ms: startMs,
        end_ms: endMs,
        caption_language: captionLanguage,
        caption_track_kind: captionTrackKind,
      },
    }),
    { sourceTitle: "Video One", selectedTraceRef },
  );
}

describe("source reader model", () => {
  it("normalizes live Telegram items with reply, reaction, topic, and media metadata", () => {
    const item = sourceItem({
      hasMedia: true,
      mediaKind: "photo",
      mediaSummary: "Image 1200x800",
      mediaFileName: "image.jpg",
      mediaMimeType: "image/jpeg",
      forumTopicId: 7,
      forumTopicTitle: "Announcements",
      replyToMessageId: 99,
      replyToTopMessageId: 7,
      reactionCount: 3,
    });

    const readerItem = sourceItemToReaderItem(item, { sourceTitle: "Telegram A" });

    expect(readerItem.kind).toBe("telegram_message");
    expect(readerItem.sourceId).toBe(10);
    expect(readerItem.sourceTitle).toBe("Telegram A");
    expect(readerItem.topicLabel).toBe("Announcements");
    expect(readerItem.replyLabel).toBe("Reply to #99");
    expect(readerItem.reactionLabel).toBe("3 reactions");
    expect(readerItem.mediaCards).toEqual([
      {
        kind: "photo",
        title: "Image",
        summary: "Image 1200x800",
        fileName: "image.jpg",
        mimeType: "image/jpeg",
      },
    ]);
  });

  it("exposes provider-neutral live item refs for trace selection", () => {
    const readerItem = sourceItemToReaderItem(sourceItem(), {
      sourceTitle: "Telegram A",
      selectedTraceRef: "s10-i1",
    });

    expect(readerItem.ref).toBe("s10-i1");
    expect(readerItem.selected).toBe(true);
  });

  it("exposes timestamped YouTube segment refs for trace selection", () => {
    const readerItem = youtubeSegmentToReaderItem(youtubeSegment(), {
      sourceTitle: "Video One",
      canonicalUrl: "https://www.youtube.com/watch?v=v1",
      selectedTraceRef: "s20-i4@754000ms",
    });

    expect(readerItem.ref).toBe("s20-i4@754000ms");
    expect(readerItem.selected).toBe(true);
    expect(readerItem.youtubeUrl).toBe("https://www.youtube.com/watch?v=v1&t=754");
  });

  it("normalizes run snapshot YouTube transcript metadata", () => {
    const readerItem = analysisRunMessageToReaderItem(runMessage(), { sourceTitle: "Video One" });

    expect(readerItem.kind).toBe("youtube_transcript");
    expect(readerItem.ref).toBe("s20-i4@754000ms");
    expect(readerItem.youtubeStartSeconds).toBe(754);
    expect(readerItem.youtubeUrl).toBe("https://www.youtube.com/watch?v=v1&t=754");
    expect(readerItem.captionLabel).toBe("en manual");
  });

  it("groups reader items by source without merging unrelated source material", () => {
    const groups = groupReaderItemsBySource([
      analysisRunMessageToReaderItem(runMessage({ source_id: 2, ref: "s2-i1" }), {
        sourceTitle: "Source 2",
      }),
      analysisRunMessageToReaderItem(runMessage({ source_id: 1, ref: "s1-i1" }), {
        sourceTitle: "Source 1",
      }),
    ]);

    expect(groups.map((group) => group.sourceId)).toEqual([1, 2]);
    expect(groups[0].sourceTitle).toBe("Source 1");
    expect(groups[1].sourceTitle).toBe("Source 2");
  });

  it("groups timeline items by UTC day", () => {
    const groups = groupReaderItemsByDay([
      sourceItemToReaderItem(sourceItem({ id: 1, publishedAt: 1710020000 }), {
        sourceTitle: "A",
      }),
      sourceItemToReaderItem(sourceItem({ id: 2, publishedAt: 1709900000 }), {
        sourceTitle: "A",
      }),
    ]);

    expect(groups).toHaveLength(2);
    expect(groups[0].items[0].id).toBe("live:1");
  });

  it("formats YouTube timestamps and appends canonical time links", () => {
    expect(formatYoutubeTime(0)).toBe("0:00");
    expect(formatYoutubeTime(754)).toBe("12:34");
    expect(formatYoutubeTime(754.9)).toBe("12:34");
    expect(formatYoutubeTime(3723)).toBe("1:02:03");
    expect(youtubeTimestampUrl("https://www.youtube.com/watch?v=v1", 754)).toBe(
      "https://www.youtube.com/watch?v=v1&t=754",
    );
    expect(youtubeTimestampUrl("https://www.youtube.com/watch?v=v1&t=1", 754)).toBe(
      "https://www.youtube.com/watch?v=v1&t=754",
    );
    expect(youtubeTimestampUrl("not a url", 754)).toBeNull();
  });

  it("builds source focus options from loaded reader items", () => {
    const options = sourceFilterOptionsFromReaderItems([
      analysisRunMessageToReaderItem(runMessage({ source_id: 2, ref: "s2-i1" }), {
        sourceTitle: "Source 2",
      }),
      analysisRunMessageToReaderItem(runMessage({ source_id: 1, ref: "s1-i1" }), {
        sourceTitle: "Source 1",
      }),
      analysisRunMessageToReaderItem(runMessage({ source_id: 2, ref: "s2-i2" }), {
        sourceTitle: "Source 2",
      }),
    ]);

    expect(options).toEqual([
      { id: 1, label: "Source 1", count: 1 },
      { id: 2, label: "Source 2", count: 2 },
    ]);
  });

  it("builds source focus options from every group member even before items load", () => {
    const options = sourceFilterOptionsFromGroupMembers([
      { source_id: 8, source_title: "Loaded", item_count: 10 },
      { source_id: 9, source_title: "Not loaded yet", item_count: 20 },
    ]);

    expect(options).toEqual([
      { id: 8, label: "Loaded", count: 10 },
      { id: 9, label: "Not loaded yet", count: 20 },
    ]);
  });

  it("joins nearby short YouTube transcript segments into one reading group", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: "This is the first caption", startMs: 0, endMs: 1400 }),
      transcriptItem({
        ref: "s20-i4@1500ms",
        content: "and this continues the same thought.",
        startMs: 1500,
        endMs: 2800,
      }),
    ]);

    expect(groups).toHaveLength(1);
    expect(groups[0]).toMatchObject({
      id: "transcript-group:snapshot:s20-i4@0ms",
      startSeconds: 0,
      content: "This is the first caption and this continues the same thought.",
      refs: ["s20-i4@0ms", "s20-i4@1500ms"],
    });
  });

  it("starts a new transcript group when a timed pause reaches two seconds", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: "First thought.", startMs: 0, endMs: 1000 }),
      transcriptItem({ ref: "s20-i4@3000ms", content: "Second thought.", startMs: 3000, endMs: 4000 }),
    ]);

    expect(groups.map((group) => group.content)).toEqual(["First thought.", "Second thought."]);
  });

  it("does not infer a timed pause when the previous segment has no end timestamp", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: "First caption", startMs: 0, endMs: null }),
      transcriptItem({ ref: "s20-i4@9000ms", content: "still joins without an end timestamp.", startMs: 9000, endMs: 10000 }),
    ]);

    expect(groups).toHaveLength(1);
    expect(groups[0].content).toBe("First caption still joins without an end timestamp.");
  });

  it("starts a new transcript group before appending text past the hard paragraph length", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: "a".repeat(550), startMs: 0, endMs: 1000 }),
      transcriptItem({ ref: "s20-i4@1100ms", content: "next segment", startMs: 1100, endMs: 1600 }),
    ]);

    expect(groups).toHaveLength(2);
    expect(groups[0].content).toHaveLength(550);
    expect(groups[1].content).toBe("next segment");
  });

  it("starts a new transcript group after preferred length when the current text ends with sentence punctuation", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: `${"a".repeat(359)}.`, startMs: 0, endMs: 1000 }),
      transcriptItem({ ref: "s20-i4@1100ms", content: "new sentence", startMs: 1100, endMs: 1600 }),
    ]);

    expect(groups.map((group) => group.content)).toEqual([`${"a".repeat(359)}.`, "new sentence"]);
  });

  it("keeps preferred-length transcript text together when sentence punctuation is missing", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: "a".repeat(360), startMs: 0, endMs: 1000 }),
      transcriptItem({ ref: "s20-i4@1100ms", content: "continued", startMs: 1100, endMs: 1600 }),
    ]);

    expect(groups).toHaveLength(1);
    expect(groups[0].content).toBe(`${"a".repeat(360)} continued`);
  });

  it("marks a transcript group selected when any included ref is selected", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: "First", startMs: 0, endMs: 1000 }),
      transcriptItem({
        ref: "s20-i4@1100ms",
        content: "selected second.",
        startMs: 1100,
        endMs: 1600,
        selectedTraceRef: "s20-i4@1100ms",
      }),
    ]);

    expect(groups).toHaveLength(1);
    expect(groups[0].selected).toBe(true);
  });

  it("keeps transcript items without start timestamps as single-item groups", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: "Timed first.", startMs: 0, endMs: 1000 }),
      transcriptItem({ ref: "s20-i4@unknown", content: "Untimed middle.", startMs: null, endMs: null }),
      transcriptItem({ ref: "s20-i4@1100ms", content: "Timed last.", startMs: 1100, endMs: 1600 }),
    ]);

    expect(groups.map((group) => group.content)).toEqual(["Timed first.", "Untimed middle.", "Timed last."]);
    expect(groups.map((group) => group.startSeconds)).toEqual([0, null, 1]);
  });

  it("uses shared transcript metadata only when all grouped items match", () => {
    const groups = groupYoutubeTranscriptItems([
      transcriptItem({ ref: "s20-i4@0ms", content: "First", startMs: 0, endMs: 1000 }),
      transcriptItem({
        ref: "s21-i4@1100ms",
        content: "second.",
        startMs: 1100,
        endMs: 1600,
        sourceId: 21,
        captionLanguage: "ru",
      }),
    ]);

    expect(groups).toHaveLength(1);
    expect(groups[0].captionLabel).toBeNull();
    expect(groups[0].sourceId).toBeNull();
  });
});
