[graph]
targets = ["x86_64-pc-windows-msvc"]

[advisories]
unmaintained = "workspace"
unsound = "all"
yanked = "warn"

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[licenses]
unused-allowed-license = "deny"
unused-license-exception = "deny"
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "MIT-0",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]

[licenses.private]
ignore = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
