import { cleanup, fireEvent, render, screen } from "@testing-library/svelte";
import { afterEach, describe, expect, it, vi } from "vitest";
import YoutubeTranscriptReader from "./youtube-transcript-reader.svelte";
import type { YoutubeVideoDetail } from "$lib/types/youtube";

afterEach(cleanup);

function videoDetail(): YoutubeVideoDetail {
  return {
    summary: {
      sourceId: 1,
      sourceSubtype: "video",
      title: "Rendered video title",
      channelTitle: "Research channel",
      channelHandle: "@research",
      canonicalUrl: "https://www.youtube.com/watch?v=video-1",
      thumbnailUrl: null,
      durationSeconds: 120,
      publishedAt: 1_700_000_000,
      availabilityStatus: "available",
      videoCount: null,
      linkedVideoCount: null,
      unavailableCount: null,
      captions: { state: "synced", itemCount: 1, segmentCount: 3, lastSyncedAt: 1_700_000_000, label: "Captions synced" },
      comments: { state: "synced", itemCount: 2, segmentCount: 0, lastSyncedAt: 1_700_000_000, label: "Comments synced" },
    },
    sourceMetadata: {
      sourceId: 1,
      videoId: "video-1",
      canonicalUrl: "https://www.youtube.com/watch?v=video-1",
      title: "Rendered video title",
      channelTitle: "Research channel",
      channelId: "channel-1",
      channelHandle: "@research",
      channelUrl: "https://www.youtube.com/@research",
      authorDisplay: "Research channel",
      publishedAt: 1_700_000_000,
      durationSeconds: 120,
      description: "Research description",
      thumbnailUrl: null,
      viewCount: 100,
      likeCount: 10,
      commentCount: 2,
      category: "Education",
      videoForm: "long",
      availabilityStatus: "available",
      captionLanguageOverride: null,
      rawMetadataVersion: 1,
      rawMetadataJson: null,
    },
    playlistMemberships: [],
  };
}

describe("analysis redesign final safety contract", () => {
  it("renders YouTube source material as transcript and playlist readers without an embedded player", async () => {
    const onChangeTranscriptSearch = vi.fn();
    const view = render(YoutubeTranscriptReader, {
      props: {
        detail: videoDetail(),
        segments: [{ id: 3, sourceId: 1, itemId: 1, segmentIndex: 0, startMs: 1_000, endMs: 2_000, text: "Timestamp-backed transcript evidence", captionLanguage: "en", captionTrackKind: "manual", isAutoGenerated: false }],
        snapshotItems: [],
        loading: false,
        hasMore: false,
        transcriptSearch: "",
        sourceTitle: "Fallback video title",
        selectedTraceRef: null,
        formatTimestamp: (value) => value === null ? "Never" : `time:${value}`,
        onChangeTranscriptSearch,
        onLoadMore: vi.fn(),
        onSyncTranscript: vi.fn(),
        onSyncMetadata: vi.fn(),
        onSyncComments: vi.fn(),
      },
    });

    expect(screen.getByRole("region", { name: "YouTube transcript reader" })).toBeTruthy();
    expect(screen.getByRole("heading", { name: "Rendered video title" })).toBeTruthy();
    expect(screen.getByRole("searchbox", { name: "Search transcript" })).toBeTruthy();
    expect(screen.getByText("Captions synced")).toBeTruthy();
    expect(screen.getByText("3 segments")).toBeTruthy();
    expect(screen.getByText("Comments synced")).toBeTruthy();
    expect(screen.getByText("2 comments")).toBeTruthy();
    expect(screen.getByText("Timestamp-backed transcript evidence")).toBeTruthy();
    const timestamp = screen.getByRole("link", { name: /0:01/ });
    expect(timestamp.getAttribute("href")).toContain("t=1");
    expect(timestamp.getAttribute("rel")).toBe("noopener noreferrer");
    expect(screen.getByRole("button", { name: "Copy timestamp link" })).toBeTruthy();
    expect(screen.getByRole("button", { name: "Sync metadata" })).toBeTruthy();
    expect(screen.getByRole("button", { name: "Sync transcript" })).toBeTruthy();
    expect(screen.getByRole("button", { name: "Sync comments" })).toBeTruthy();
    await fireEvent.input(screen.getByRole("searchbox", { name: "Search transcript" }), { target: { value: "evidence" } });
    expect(onChangeTranscriptSearch).toHaveBeenCalledWith("evidence");
    expect(view.container.querySelector("iframe, video")).toBeNull();
  });
});
