import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/svelte";
import "$lib/testing/dom-assertions";
const api = vi.hoisted(() => ({ getPromptPackResult: vi.fn(), getPromptPackStageArtifact: vi.fn(), getPromptPackValidationFindings: vi.fn(), listPromptPackAuditEvents: vi.fn(), listPromptPackRunStages: vi.fn(), listPromptPackStageArtifacts: vi.fn() }));
vi.mock("$lib/api/prompt-packs", () => api);
import ProjectRunReportPanel from "./ProjectRunReportPanel.svelte";
const run = (overrides = {}) => ({ runId: 91, projectId: 5, runLabel: "Evidence report", runtimeProvider: "gemini_browser", packId: "youtube-summary", packVersion: "1", runStatus: "complete", resultStatus: "complete", latestMessage: "Complete", ...overrides });
const canonical = { pack_version: "1", output_language: "en", source_refs: [{ source_ref_id: "src-1" }], claims: [{ claim_id: "claim-1", source_ref_id: "src-1", text: "Common claim" }], evidence: [{ evidence_id: "ev-1", source_ref_id: "src-1", text: "Evidence fragment" }], warnings: [{ message: "Warning one" }], limitations: [{ message: "Limitation one" }], quality_flags: [{ message: "Quality one" }], outputs: { sections: [{ section_id: "section_summary", body: "Readable summary" }], pack_data: { youtube_summary: { videos: [{ video_id: "video-1", source_ref_id: "src-1", title: "Evidence video", summary_text: "**Video** summary" }], segments: [{ start_seconds: 1, end_seconds: 2, text: "Timeline" }], key_points: [{ text: "Key point" }], quotes: [{ text: "Quote" }], action_items: [{ text: "Action" }], open_questions: [{ text: "Question" }], synthesis_items: [], synthesis: { cross_video_themes: [{ theme_text: "Theme" }], common_claims: [{ summary_text: "Shared", source_refs: ["src-1"] }], contradictions_across_videos: [{ description: "Difference" }], source_refs: ["src-1"] } } } } };
const result = { resultStatus: "complete", canonical };
const stage = { stageRunId: 7, stageName: "reduce", stageStatus: "completed", latestMessage: "Stage done", browserRunId: "browser-1", browserRunStatus: "completed", browserCompletionReason: "answer_detected", browserProviderMode: "managed", browserRunMessage: "Browser done" };
const artifact = { stageRunId: 7, artifactKind: "parsed_output", attemptNumber: 1, artifactIndex: 0, content: { answer: "artifact" }, contentType: "application/json" };
beforeEach(() => { api.getPromptPackResult.mockResolvedValue(result); api.listPromptPackRunStages.mockResolvedValue([stage]); api.getPromptPackValidationFindings.mockResolvedValue([{ severity: "warning", code: "vf", message: "Finding", createdAt: "now" }]); api.listPromptPackAuditEvents.mockResolvedValue([{ eventKind: "completed", message: "Audit complete", createdAt: "now" }]); api.listPromptPackStageArtifacts.mockResolvedValue([{ stageRunId: 7, artifactKind: "parsed_output", attemptNumber: 1, artifactIndex: 0 }]); api.getPromptPackStageArtifact.mockResolvedValue(artifact); vi.stubGlobal("navigator", { clipboard: { writeText: vi.fn().mockResolvedValue(undefined) } }); });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.clearAllMocks(); });
async function mount(overrides = {}) { render(ProjectRunReportPanel, { run: run(overrides) as never }); await screen.findByText("Readable summary"); await screen.findByText("reduce"); await waitFor(() => { if (screen.getByRole("button", { name: "Refresh run report" }).hasAttribute("disabled")) throw new Error("report still loading"); }); }
describe("project runs screen", () => {
  it("renders a from-scratch prompt-pack report workspace under the grid", async () => { await mount(); const report = screen.getByRole("region", { name: "Project run report" }); expect(report).toBeTruthy(); expect(within(report).getByRole("heading", { name: "Evidence report" })).toBeTruthy(); expect(within(report).getByRole("heading", { name: "Result" })).toBeTruthy(); expect(within(report).getByText("Readable summary")).toBeTruthy(); expect(within(report).getByRole("heading", { name: "Stages and Artifacts" })).toBeTruthy(); expect(within(report).getByText("reduce")).toBeTruthy(); expect(within(report).getByRole("button", { name: "Refresh run report" })).toBeEnabled(); expect(api.getPromptPackResult).toHaveBeenCalledWith(91); });
  it("formats object-shaped prompt-pack report errors instead of rendering raw objects", async () => { api.getPromptPackResult.mockRejectedValue({ code: "RESULT_MISSING", message: "Result unavailable" }); api.getPromptPackStageArtifact.mockRejectedValue({ code: "ARTIFACT_MISSING", message: "Artifact unavailable" }); render(ProjectRunReportPanel, { run: run() as never }); const resultMessage = await screen.findByText(/Result unavailable/); expect(resultMessage.textContent).toContain("Result unavailable"); expect(resultMessage.textContent).not.toContain("[object Object]"); await fireEvent.click(await screen.findByRole("button", { name: /parsed_output/ })); const artifactMessage = await screen.findByText(/Artifact unavailable/); expect(artifactMessage.textContent).toContain("Artifact unavailable"); expect(screen.queryByText("[object Object]")).toBeNull(); });
  it("keeps diagnostics visible when a run has no canonical result yet", async () => { api.getPromptPackResult.mockRejectedValue(new Error("not ready")); render(ProjectRunReportPanel, { run: run({ runStatus: "running", resultStatus: "none" }) as never }); await screen.findByText("Stage done"); expect(screen.getByRole("heading", { name: "Stages and Artifacts" })).toBeTruthy(); expect(screen.getByText("reduce")).toBeTruthy(); expect(screen.getByText("Stage done")).toBeTruthy(); expect(screen.getByText(/canonical result/i)).toBeTruthy(); expect(api.listPromptPackRunStages).toHaveBeenCalledWith(91); expect(screen.getByRole("button", { name: /parsed_output/ })).toBeTruthy(); });
  it("renders canonical youtube synthesis groups with a reference rail", async () => { await mount(); const rail = screen.getByRole("complementary", { name: "Synthesis references" }); expect(screen.getByRole("heading", { name: "Synthesis" })).toBeTruthy(); expect(screen.getByRole("heading", { name: "Cross-video themes" })).toBeTruthy(); expect(screen.getByText("Theme")).toBeTruthy(); expect(screen.getByRole("heading", { name: "Common claims" })).toBeTruthy(); expect(screen.getByText("Shared")).toBeTruthy(); expect(screen.getByRole("heading", { name: "Contradictions" })).toBeTruthy(); expect(screen.getByText("Difference")).toBeTruthy(); expect(rail).toBeTruthy(); expect(within(rail).getByRole("button", { name: "src-1" })).toBeTruthy(); expect(screen.getByText((_, element) => element?.tagName === "SPAN" && element.textContent === "Themes 1")).toBeTruthy(); expect(screen.getByText((_, element) => element?.tagName === "SPAN" && element.textContent === "Contradictions 1")).toBeTruthy(); });
  it("renders readable summary sections when canonical outputs.summary is absent", async () => { await mount(); expect(screen.getByText("Readable summary")).toBeTruthy(); expect(screen.getByText("Readable summary").tagName).toBe("P"); expect(screen.getByRole("heading", { name: "Result" })).toBeTruthy(); });
  it("makes report references clickable and highlights matching canonical items", async () => { await mount(); const ref = screen.getAllByRole("button", { name: "src-1" })[0]; expect(ref).toBeTruthy(); await fireEvent.click(ref); expect(ref.getAttribute("aria-pressed")).toBe("true"); expect(screen.getByText("Selected ref")).toBeTruthy(); expect(screen.getByText("src-1", { selector: "strong" })).toBeTruthy(); expect(document.querySelectorAll(".ref-target").length).toBeGreaterThan(0); expect(document.querySelector('[data-ref-targets~="src-1"]')).toBeTruthy(); expect(screen.getByRole("button", { name: "Clear" })).toBeTruthy(); await fireEvent.click(screen.getByRole("button", { name: "Clear" })); expect(screen.queryByText("Selected ref")).toBeNull(); });
  it("renders selected artifacts with typed previews and copy support", async () => { await mount(); const artifactButton = screen.getByRole("button", { name: /parsed_output/ }); expect(artifactButton).toBeTruthy(); await fireEvent.click(artifactButton); await screen.findAllByRole("heading", { name: "Parsed output" }); expect(api.getPromptPackStageArtifact).toHaveBeenCalledWith({ stageRunId: 7, artifactKind: "parsed_output", attemptNumber: 1, artifactIndex: 0 }); expect(screen.getAllByRole("heading", { name: "Parsed output" }).length).toBe(2); expect(screen.getAllByText(/artifact/).length).toBeGreaterThan(0); expect(screen.getByText("application/json")).toBeTruthy(); expect(screen.getByText(/attempt 1/)).toBeTruthy(); expect(screen.getByText(/item 0/)).toBeTruthy(); const copy = screen.getByRole("button", { name: "Copy JSON" }); expect(copy).toBeEnabled(); await fireEvent.click(copy); await waitFor(() => expect(navigator.clipboard.writeText).toHaveBeenCalled()); expect(navigator.clipboard.writeText).toHaveBeenCalledOnce(); });
});
