export type TelegramSourceKind = "channel" | "supergroup" | "group";
export type SourceType = "telegram" | "youtube" | "rss" | "forum";
export type SourceSubtype =
  | TelegramSourceKind
  | "video"
  | "playlist"
  | "feed"
  | "thread"
  | "board"
  | "site";
export type SourceContentLabel = "messages" | "videos" | "posts" | "items";
export type InitialSyncMode = "recent_messages" | "recent_days";
export type YoutubePreviewKind = "video" | "playlist";
export type YoutubeAvailabilityStatus =
  | "available"
  | "upcoming"
  | "live_now"
  | "live_ended_transcript_pending"
  | "no_captions"
  | "private_or_auth_required"
  | "members_only"
  | "age_restricted"
  | "geo_blocked"
  | "deleted"
  | "removed_from_playlist"
  | "unavailable_unknown";

export type DialogKindFilter = "all" | TelegramSourceKind;

export interface TelegramDialogSource {
  id: number;
  title: string;
  username: string | null;
  sourceSubtype: TelegramSourceKind;
  isMember: boolean;
  photoDataUrl: string | null;
}

export interface Source {
  id: number;
  sourceType: SourceType;
  sourceSubtype: SourceSubtype | null;
  accountId: number | null;
  externalId: string;
  title: string | null;
  lastSyncState: number | null;
  lastSyncedAt: number | null;
  isMember: boolean;
  isActive: boolean;
  createdAt: number;
  telegramUsername: string | null;
  avatarDataUrl: string | null;
}

export interface SourceCapabilities {
  canSync: boolean;
  canDelete: boolean;
  canImportArchive: boolean;
  hasTopics: boolean;
  requiresAccount: boolean;
  hasMembershipState: boolean;
  contentLabel: SourceContentLabel;
}

export interface SourceItem {
  id: number;
  sourceId: number;
  externalId: string;
  itemKind: string;
  author: string | null;
  publishedAt: number;
  content: string | null;
  contentKind: string;
  hasMedia: boolean;
  mediaKind: string | null;
  mediaSummary: string | null;
  mediaFileName: string | null;
  mediaMimeType: string | null;
  hasRawData: boolean;
  forumTopicId: number | null;
  forumTopicTitle: string | null;
  forumTopicTopMessageId: number | null;
  replyToMessageId: number | null;
  replyToPeerKind: string | null;
  replyToPeerId: string | null;
  replyToTopMessageId: number | null;
  reactionCount: number | null;
}

export type ForumTopicFilter =
  | { kind: "topic"; topicId: number }
  | { kind: "uncategorized" };

export interface AddTelegramSourceInput {
  accountId: number;
  sourceRef: string;
  expectedSubtype: TelegramSourceKind | null;
}

export interface YoutubeCaptionsEstimate {
  hasManual: boolean;
  hasAuto: boolean;
  languages: string[];
}

export interface YoutubePreview {
  kind: YoutubePreviewKind;
  externalId: string;
  canonicalUrl: string;
  title: string | null;
  channelTitle: string | null;
  channelId: string | null;
  channelHandle: string | null;
  channelUrl: string | null;
  thumbnailUrl: string | null;
  durationSeconds: number | null;
  publishedAt: string | null;
  playlistVideoCount: number | null;
  captionsEstimate: YoutubeCaptionsEstimate | null;
  availabilityStatus: YoutubeAvailabilityStatus;
  warnings: string[];
}

export interface ListSourceItemsInput {
  sourceId: number;
  limit: number;
  beforePublishedAt: number | null;
  topicFilter: ForumTopicFilter | null;
  aroundItemId?: number | null;
}

export interface YoutubeTranscriptSegmentCursor {
  startMs: number;
  segmentId: number;
}

export interface YoutubeTranscriptSegment {
  id: number;
  sourceId: number;
  itemId: number;
  segmentIndex: number;
  startMs: number;
  endMs: number | null;
  text: string;
  captionLanguage: string | null;
  captionTrackKind: string | null;
  isAutoGenerated: boolean;
}

export interface YoutubeTranscriptSegmentsPage {
  segments: YoutubeTranscriptSegment[];
  nextCursor: YoutubeTranscriptSegmentCursor | null;
  hasMore: boolean;
}

export interface ListYoutubeTranscriptSegmentsInput {
  sourceId: number;
  after: YoutubeTranscriptSegmentCursor | null;
  limit: number;
  searchQuery: string | null;
  aroundStartMs?: number | null;
}

export interface SourceForumTopic {
  kind: "topic" | "uncategorized";
  key: string;
  title: string;
  messageCount: number;
  topicId: number | null;
  topMessageId: number | null;
  iconColor: number | null;
  iconEmojiId: number | null;
  isClosed: boolean;
  isPinned: boolean;
  isHidden: boolean;
  isDeleted: boolean;
  sortOrder: number | null;
}

export type TopicResolutionStatus = "never_run" | "ready" | "dirty" | "rebuilding" | "failed";

export interface TopicResolutionStateSummary {
  status: TopicResolutionStatus;
  resolverVersion: number;
  unresolvedCount: number;
  pendingItemCount: number;
  membershipsRefreshedAt: number | null;
}

export interface SourceForumTopicsResult {
  topics: SourceForumTopic[];
  topicResolutionState: TopicResolutionStateSummary;
}

export interface SyncSourceResult {
  inserted: number;
  skipped: number;
  lastMessageId: number | null;
  initialSyncPolicyApplied: string | null;
  warnings: string[];
}

export interface SyncSettings {
  initialSyncMode: InitialSyncMode;
  initialSyncValue: number;
}

export type SourceJobStatus =
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "cancel_requested"
  | "cancelled";

export type SourceJobType =
  | "youtube_video_metadata_sync"
  | "youtube_video_transcript_sync"
  | "youtube_video_comments_sync"
  | "youtube_video_full_sync"
  | "youtube_playlist_metadata_sync"
  | "youtube_playlist_full_sync"
  | "youtube_playlist_video_sync";

export interface YoutubeSyncOptions {
  metadata: boolean;
  transcripts: boolean;
  comments: boolean;
}

export interface SourceJobRecord {
  job_id: string;
  source_id: number;
  related_source_id: number | null;
  job_type: SourceJobType;
  status: SourceJobStatus;
  message: string | null;
  progress_current: number | null;
  progress_total: number | null;
  started_at: number;
  finished_at: number | null;
  warnings: string[];
  error: string | null;
}

export type SourceJobEvent = SourceJobRecord;

export type TakeoutImportStatus =
  | "queued"
  | "running"
  | "cancel_requested"
  | "completed"
  | "failed"
  | "cancelled";

export const TAKEOUT_IMPORT_PHASES = [
  "queued",
  "resolving_source",
  "starting_takeout",
  "validating_peer",
  "loading_splits",
  "counting",
  "importing_history",
  "finishing_takeout",
  "completed",
  "failed",
  "cancelled",
] as const;

export type TakeoutImportPhase = (typeof TAKEOUT_IMPORT_PHASES)[number];

export interface TakeoutImportJobRecord {
  job_id: string;
  source_id: number;
  account_id: number;
  status: TakeoutImportStatus;
  phase: TakeoutImportPhase;
  message: string | null;
  inserted: number;
  skipped: number;
  progress_current: number | null;
  progress_total: number | null;
  started_at: number;
  finished_at: number | null;
  warnings: string[];
  error: string | null;
}

export type TakeoutImportEvent = TakeoutImportJobRecord;

export interface StartTakeoutImportResponse {
  job_id: string;
}

export interface CancelTakeoutImportResponse {
  cancelled: boolean;
}

export interface NotebookLmExportRequest {
  export_id: string | null;
  source_id: number;
  output_dir: string;
  period_from: number | null;
  period_to: number | null;
  include_media_placeholders: boolean;
  min_message_length: number;
  max_words_per_file: number;
  max_bytes_per_file: number;
  overwrite_existing: boolean;
}

export interface NotebookLmExportFile {
  path: string;
  message_count: number;
  byte_size: number;
  approximate_word_count: number;
}

export interface NotebookLmExportResult {
  output_dir: string;
  files: NotebookLmExportFile[];
  glossary_file: string | null;
  exported_message_count: number;
  skipped_message_count: number;
  warning_count: number;
  warnings: string[];
}

export type NotebookLmExportEventKind = "started" | "progress" | "completed" | "failed";

export type NotebookLmExportPhase =
  | "loading"
  | "filtering"
  | "chunking"
  | "preparing_output"
  | "writing"
  | "manifest"
  | "completed"
  | "failed";

export interface NotebookLmExportEvent {
  export_id: string;
  source_id: number;
  kind: NotebookLmExportEventKind;
  phase: NotebookLmExportPhase;
  message: string | null;
  progress_current: number | null;
  progress_total: number | null;
  file_path: string | null;
  error: string | null;
}
